name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore GraphQL.NET.sln
    - name: Build
      run: dotnet build GraphQL.NET.sln --no-restore
    - name: Start app and test
      run : |
          sh ./scripts/run.sh
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
